### ISSUE TITLE
replace font in scene fix?

### ISSUE THREAD

**Issue by chandler55** [Son1kXDev/replacefontunity#1]
I noticed the "Current Scene" option wasn't working for me because in the code it would exit the loop once it found an object that wasn't in the scene. in my case it found a object with a textmeshpro in my project assets

so should "return" be "continue" on lines 38,71 of ReplaceFont.cs?

thanks, great tool btw

**Comment by Son1kXDev** [comment]
Thank you for this issue. The bug has been fixed, check the new release.

Also, thank you so much for using my tool! If you find any bug again or there is an idea to improve the tool - write issues, I will try to do my best.
